<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => 2,
                'nama' => 'Exsan Fensury',
                'jabatan' => 'Direktur',
                'jenis_kelamin' => 'l',
                'tempat_lahir' => 'Dabo Singkep',
                'tanggal_lahir' => '1961-06-02',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Permanen',
                'mulai_bekerja' => '2021-09-21',
                'gaji' => 4150930,
                'email' => 'user1@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 3,
                'nama' => 'Elbert Fensury',
                'jabatan' => 'Manager',
                'jenis_kelamin' => 'l',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1990-06-02',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Permanen',
                'mulai_bekerja' => '2021-09-21',
                'gaji' => 6500000,
                'email' => 'user2@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'admin',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 4,
                'nama' => 'Alvenia Nur Primadana',
                'jabatan' => 'Admin',
                'jenis_kelamin' => 'p',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '2000-09-08',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2021-09-21',
                'gaji' => 4150930,
                'email' => 'user3@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'admin',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 5,
                'nama' => 'Muhammad Adam',
                'jabatan' => 'Admin',
                'jenis_kelamin' => 'l',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '1995-01-28',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2023-08-01',
                'gaji' => 4150930,
                'email' => 'user4@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'admin',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 6,
                'nama' => ' Agus Salam Nuryahya',
                'jabatan' => 'Manager/Pengawas',
                'jenis_kelamin' => 'l',
                'tempat_lahir' => 'Kediri',
                'tanggal_lahir' => '1981-05-07',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2021-09-21',
                'gaji' => 4250000,
                'email' => 'user5@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'manajer',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 7,
                'nama' => 'Brearton Ivan Haryanto Joel Simanjutank',
                'jabatan' => 'Operator',
                'jenis_kelamin' => 'l',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1993-10-26',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2021-11-01',
                'gaji' => 3000000,
                'email' => 'user6@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 8,
                'nama' => ' Sisko Situmeang ',
                'jabatan' => 'Operator',
                'jenis_kelamin' => 'l',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '2022-01-05',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2022-01-01',
                'gaji' => 3000000,
                'email' => 'user7@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 9,
                'nama' => 'Muhamad Rizky',
                'jabatan' => 'Operator',
                'jenis_kelamin' => 'l',
                'tempat_lahir' => 'Batam',
                'tanggal_lahir' => '2000-05-23',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2022-10-01',
                'gaji' => 3000000,
                'email' => 'user8@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 10,
                'nama' => 'Setiyo Raharjo',
                'jabatan' => 'Operator',
                'jenis_kelamin' => 'l',
                'tempat_lahir' => 'Purwokerto',
                'tanggal_lahir' => '1995-06-05',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2022-10-01',
                'gaji' => 3000000,
                'email' => 'user9@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 11,
                'nama' => 'Bobi',
                'jabatan' => 'Operator',
                'jenis_kelamin' => 'l',
                'tempat_lahir' => 'Tangga Bosi',
                'tanggal_lahir' => '1995-04-16',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2022-12-01',
                'gaji' => 3000000,
                'email' => 'user10@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 12,
                'nama' => 'Wahidah Daulay',
                'jabatan' => 'Operator',
                'jenis_kelamin' => 'p',
                'tempat_lahir' => 'Sungai Salak',
                'tanggal_lahir' => '2002-12-20',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2022-12-01',
                'gaji' => 3000000,
                'email' => 'user11@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 13,
                'nama' => 'Richi Renaldy',
                'jabatan' => 'Pengawas',
                'jenis_kelamin' => 'l',
                'tempat_lahir' => 'Dabo Singkep',
                'tanggal_lahir' => '1997-09-27',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2021-09-21',
                'gaji' => 4150930,
                'email' => 'user12@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'pengawas',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 14,
                'nama' => 'Devita Yanti Suryani sitanggang',
                'jabatan' => 'Operator',
                'jenis_kelamin' => 'p',
                'tempat_lahir' => 'Tebing Tinggi',
                'tanggal_lahir' => '2002-03-24',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2021-09-21',
                'gaji' => 3500000,
                'email' => 'user13@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 15,
                'nama' => 'Syammir Walid Daulay',
                'jabatan' => 'Asisten Pengawas',
                'jenis_kelamin' => 'l',
                'tempat_lahir' => 'Binjai',
                'tanggal_lahir' => '1998-10-25',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2021-09-21',
                'gaji' => 3000000,
                'email' => 'user14@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 16,
                'nama' => 'Yanto Julius Peni',
                'jabatan' => 'Operator',
                'jenis_kelamin' => 'l',
                'tempat_lahir' => 'Kalabahi',
                'tanggal_lahir' => '1994-07-03',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2021-07-01',
                'gaji' => 3000000,
                'email' => 'user15@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 17,
                'nama' => 'Zarfin Elisma ',
                'jabatan' => 'Operator',
                'jenis_kelamin' => 'l',
                'tempat_lahir' => 'Pekanbaru',
                'tanggal_lahir' => '1998-11-16',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2021-07-01',
                'gaji' => 3000000,
                'email' => 'user16@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 18,
                'nama' => 'Winston Situromang',
                'jabatan' => 'Operator',
                'jenis_kelamin' => 'l',
                'tempat_lahir' => 'Sibolga',
                'tanggal_lahir' => '2003-04-04',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2021-07-01',
                'gaji' => 3000000,
                'email' => 'user17@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 19,
                'nama' => 'Rosalina Lasmaria Siregar',
                'jabatan' => 'Operator',
                'jenis_kelamin' => 'p',
                'tempat_lahir' => 'Batam',
                'tanggal_lahir' => '2004-07-05',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2023-06-01',
                'gaji' => 3000000,
                'email' => 'user18@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 20,
                'nama' => 'Rizal',
                'jabatan' => 'Security',
                'jenis_kelamin' => 'l',
                'tempat_lahir' => 'Lampung',
                'tanggal_lahir' => '1969-08-14',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2021-12-01',
                'gaji' => 3000000,
                'email' => 'user19@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 21,
                'nama' => 'Boy Arjuna Pakpahan',
                'jabatan' => 'Asisten Pengawas',
                'jenis_kelamin' => 'l',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '2001-06-15',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2021-12-01',
                'gaji' => 3500000,
                'email' => 'user20@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 22,
                'nama' => 'Solemantang',
                'jabatan' => 'Penjaga malam',
                'jenis_kelamin' => 'l',
                'tempat_lahir' => 'NTT',
                'tanggal_lahir' => '1983-08-22',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2021-09-21',
                'gaji' => 1000000,
                'email' => 'user21@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 23,
                'nama' => 'Frans',
                'jabatan' => 'Maintenance',
                'jenis_kelamin' => 'l',
                'tempat_lahir' => 'NTT',
                'tanggal_lahir' => '1978-02-06',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2021-09-21',
                'gaji' => 1500000,
                'email' => 'user22@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 24,
                'nama' => 'Ribka Tang',
                'jabatan' => 'CS',
                'jenis_kelamin' => 'p',
                'tempat_lahir' => 'NTT',
                'tanggal_lahir' => '1978-01-10',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2021-09-21',
                'gaji' => 1000000,
                'email' => 'user23@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 25,
                'nama' => 'Pasaribu',
                'jabatan' => 'Keamanan',
                'jenis_kelamin' => 'l',
                'tempat_lahir' => 'Mojokerto',
                'tanggal_lahir' => '1985-08-12',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2021-09-21',
                'gaji' => 1000000,
                'email' => 'user24@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 26,
                'nama' => 'Simsoon Neferson maro',
                'jabatan' => 'Penjaga malam',
                'jenis_kelamin' => 'l',
                'tempat_lahir' => 'NTT',
                'tanggal_lahir' => '1970-10-20',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2021-09-21',
                'gaji' => 1000000,
                'email' => 'user25@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 27,
                'nama' => 'Widarda',
                'jabatan' => 'Maintenance',
                'jenis_kelamin' => 'l',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1980-12-04',
                'alamat' => '',
                'no_hp' => '',
                'status' => 'Kontrak',
                'mulai_bekerja' => '2022-01-01',
                'gaji' => 2000000,
                'email' => 'user26@gmail.com',
                'password' => Hash::make('secret'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now()
            ],
        ];
        DB::table('users')->insert([
            'id' => 1,
            'nama' => 'admin',
            'email' => 'admin@softui.com',
            'password' => Hash::make('secret'),
            'role' => 'superadmin',
            'created_at' => now(),
            'updated_at' => now()
        ]);
        DB::table('users')->insert($data);
    }
}